apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ppxai-registry
  namespace: ppxai-system
  labels:
    app.kubernetes.io/name: ppxai
    app.kubernetes.io/component: session-manager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ppxai-workspace
  resources:
    requests:
      storage: {{ .Values.registry.storageSize }}
