apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ppxai-workspace
  labels:
    app.kubernetes.io/name: ppxai
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
