apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ppxai-ephemeral
  labels:
    app.kubernetes.io/name: ppxai
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
