# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for ppxai-server (HTTP + SSE server for VSCode extension)

block_cipher = None

a = Analysis(
    ['ppxai-server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('.env.example', '.'),
        ('ppxai-config.example.json', '.'),
    ],
    hiddenimports=[
        # Core dependencies
        'openai',
        'httpx',
        'rich',
        'dotenv',
        # FastAPI and ASGI stack
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.responses',
        'starlette',
        'starlette.responses',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.requests',
        'starlette.datastructures',
        'starlette.exceptions',
        'starlette.status',
        # Uvicorn
        'uvicorn',
        'uvicorn.config',
        'uvicorn.main',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        # Pydantic (for FastAPI models)
        'pydantic',
        'pydantic.fields',
        'pydantic.main',
        'pydantic_core',
        # HTTP libraries
        'h11',
        'httptools',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',
        # SSL/encoding
        'certifi',
        'idna',
        'charset_normalizer',
        # Engine dependencies
        'ppxai',
        'ppxai.engine',
        'ppxai.engine.client',
        'ppxai.engine.session',
        'ppxai.engine.types',
        'ppxai.engine.providers',
        'ppxai.engine.providers.base',
        'ppxai.engine.providers.perplexity',
        'ppxai.engine.providers.openai_compat',
        'ppxai.engine.providers.gemini',
        # typing_extensions (needed by pydantic, google.genai.types, etc.)
        'typing_extensions',
        # Google Gemini native SDK (optional, for grounding)
        'google',
        'google.genai',
        'google.genai._adapters',
        'google.genai._api_client',
        'google.genai._api_module',
        'google.genai._automatic_function_calling_util',
        'google.genai._base_transformers',
        'google.genai._base_url',
        'google.genai._common',
        'google.genai._extra_utils',
        'google.genai._live_converters',
        'google.genai._mcp_utils',
        'google.genai._operations_converters',
        'google.genai._replay_api_client',
        'google.genai._transformers',
        'google.genai._tokens_converters',
        'google.genai.batches',
        'google.genai.caches',
        'google.genai.chats',
        'google.genai.client',
        'google.genai.documents',
        'google.genai.errors',
        'google.genai.files',
        'google.genai.interactions',
        'google.genai.live',
        'google.genai.live_music',
        'google.genai.models',
        'google.genai.operations',
        'google.genai.pagers',
        'google.genai.tokens',
        'google.genai.tunings',
        'google.genai.types',
        'google.genai.version',
        'google.auth',
        'google.auth.transport',
        'google.auth.transport.requests',
        'google.auth.crypt',
        'google.auth.crypt._cryptography_rsa',
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.asymmetric',
        'cryptography.hazmat.primitives.asymmetric.rsa',
        'cryptography.hazmat.backends',
        # websockets (required by google.genai live/streaming + uvicorn)
        'websockets',
        'websockets.asyncio',
        'websockets.asyncio.client',
        'websockets.asyncio.connection',
        'websockets.asyncio.server',
        'websockets.client',
        'websockets.connection',
        'websockets.exceptions',
        'websockets.frames',
        'websockets.http11',
        'websockets.imports',
        'websockets.legacy',
        'websockets.legacy.client',
        'cachetools',
        'tenacity',
        'requests',
        'urllib3',
        'pyasn1',
        'pyasn1_modules',
        'rsa',
        'ppxai.engine.tools',
        'ppxai.engine.tools.base',
        'ppxai.engine.tools.manager',
        'ppxai.config',
        'ppxai.server',
        'ppxai.server.http',
        'ppxai.common.preview',
        # Timezone support
        'tzdata',
        'zoneinfo',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['rthooks/rthook_sigint.py'],
    excludes=[
        # Exclude development/testing packages
        'pytest',
        'pytest_asyncio',
        'ruff',
        # Exclude tkinter (not needed for server)
        'tkinter',
        '_tkinter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ppxai-server',
    debug=False,
    bootloader_ignore_signals=True,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/ppxai.ico',
)
