# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

a = Analysis(
    ['ppxai.py'],
    pathex=[os.getcwd()],
    binaries=[],
    datas=[
        ('.env.example', '.'),
        ('ppxai-config.example.json', '.'),
    ],
    hiddenimports=[
        'openai',
        'rich',
        'rich.prompt',
        'rich.console',
        'rich.markdown',
        'rich.syntax',
        'rich.table',
        'rich.panel',
        'rich.live',
        'rich.spinner',
        'rich.progress',
        'prompt_toolkit',
        'prompt_toolkit.completion',
        'prompt_toolkit.history',
        'prompt_toolkit.shortcuts',
        'dotenv',
        # Explicitly include all ppxai modules
        'ppxai',
        'ppxai.main',
        'ppxai.config',
        'ppxai.constants',
        'ppxai.checkpoint',
        'ppxai.usage',
        'ppxai.version',
        'ppxai.prompts',
        'ppxai.data',
        'ppxai.data.parsers',
        'ppxai.commands',
        'ppxai.commands.handler',
        'ppxai.commands.context',
        'ppxai.commands.session',
        'ppxai.commands.provider',
        'ppxai.commands.system',
        'ppxai.commands.ui',
        'ppxai.commands.coding',
        'ppxai.commands.agent',
        'ppxai.commands.results',
        'ppxai.engine',
        'ppxai.engine.client',
        'ppxai.engine.types',
        'ppxai.engine.session',
        'ppxai.engine.context',
        'ppxai.engine.providers',
        'ppxai.engine.providers.base',
        'ppxai.engine.providers.openai_compat',
        'ppxai.engine.providers.perplexity',
        'ppxai.engine.providers.autorouter',
        'ppxai.engine.tools',
        'ppxai.engine.tools.manager',
        'ppxai.engine.tools.parser',
        'ppxai.engine.tools.builtin',
        'ppxai.rendering',
        'ppxai.rendering.rich_renderer',
        'ppxai.rich',
        'ppxai.rich.main',
        'ppxai.rich.ui',
        'ppxai.rich.utils',
        'ppxai.common',
        'ppxai.common.event_handler',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ppxai',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/ppxai-tui.ico',
)
