# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for ppxai-server (HTTP + SSE server for VSCode extension)

block_cipher = None

a = Analysis(
    ['ppxai-server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('ppxai/engine/app_state_schema.json', 'ppxai/engine'),
        ('.env.example', '.'),
        ('ppxai-config.example.json', '.'),
    ],
    hiddenimports=[
        # Core dependencies
        'openai',
        'httpx',
        'rich',
        'dotenv',
        # FastAPI and ASGI stack
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.responses',
        'starlette',
        'starlette.responses',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.requests',
        'starlette.datastructures',
        'starlette.exceptions',
        'starlette.status',
        # Uvicorn
        'uvicorn',
        'uvicorn.config',
        'uvicorn.main',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        # Pydantic (for FastAPI models)
        'pydantic',
        'pydantic.fields',
        'pydantic.main',
        'pydantic_core',
        # HTTP libraries
        'h11',
        'httptools',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',
        # SSL/encoding
        'certifi',
        'idna',
        'charset_normalizer',
        # Engine dependencies
        'ppxai',
        'ppxai.engine',
        'ppxai.engine.client',
        'ppxai.engine.session',
        'ppxai.engine.types',
        'ppxai.engine.providers',
        'ppxai.engine.providers.base',
        'ppxai.engine.providers.perplexity',
        'ppxai.engine.providers.openai_compat',
        'ppxai.engine.providers.gemini',
        # typing_extensions (needed by pydantic, google.genai.types, etc.)
        'typing_extensions',
        # Google Gemini native SDK (optional, for grounding)
        'google',
        'google.genai',
        'google.genai._adapters',
        'google.genai._api_client',
        'google.genai._api_module',
        'google.genai._automatic_function_calling_util',
        'google.genai._base_transformers',
        'google.genai._base_url',
        'google.genai._common',
        'google.genai._extra_utils',
        'google.genai._live_converters',
        'google.genai._mcp_utils',
        'google.genai._operations_converters',
        'google.genai._replay_api_client',
        'google.genai._transformers',
        'google.genai._tokens_converters',
        'google.genai.batches',
        'google.genai.caches',
        'google.genai.chats',
        'google.genai.client',
        'google.genai.documents',
        'google.genai.errors',
        'google.genai.files',
        'google.genai.interactions',
        'google.genai.live',
        'google.genai.live_music',
        'google.genai.models',
        'google.genai.operations',
        'google.genai.pagers',
        'google.genai.tokens',
        'google.genai.tunings',
        'google.genai.types',
        'google.genai.version',
        'google.auth',
        'google.auth.transport',
        'google.auth.transport.requests',
        'google.auth.crypt',
        'google.auth.crypt._cryptography_rsa',
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.asymmetric',
        'cryptography.hazmat.primitives.asymmetric.rsa',
        'cryptography.hazmat.backends',
        # websockets (required by google.genai live/streaming + uvicorn)
        'websockets',
        'websockets.asyncio',
        'websockets.asyncio.client',
        'websockets.asyncio.connection',
        'websockets.asyncio.server',
        'websockets.client',
        'websockets.connection',
        'websockets.exceptions',
        'websockets.frames',
        'websockets.http11',
        'websockets.imports',
        'websockets.legacy',
        'websockets.legacy.client',
        'cachetools',
        'tenacity',
        'requests',
        'urllib3',
        'pyasn1',
        'pyasn1_modules',
        'rsa',
        'ppxai.engine.tools',
        'ppxai.engine.tools.base',
        'ppxai.engine.tools.manager',
        'ppxai.config',
        'ppxai.config.providers',
        'ppxai.config.tools',
        'ppxai.config.features',
        'ppxai.config.paths',
        'ppxai.config.prompts',
        'ppxai.server',
        'ppxai.server.http',
        'ppxai.server.models',
        'ppxai.server.state',
        'ppxai.server.streaming',
        'ppxai.server.routes',
        # Every route module under ppxai.server.routes — listed
        # explicitly (v1.18.0) so PyInstaller's frozen bundle doesn't
        # rely on the routes/__init__.py import cascade, which is more
        # fragile in some frozen-bundle scenarios than a direct
        # hiddenimport reference.
        'ppxai.server.routes.agent',
        'ppxai.server.routes.chat',
        'ppxai.server.routes.checkpoints',
        'ppxai.server.routes.commands',
        'ppxai.server.routes.completion',
        'ppxai.server.routes.config',
        'ppxai.server.routes.consent',
        'ppxai.server.routes.context',
        'ppxai.server.routes.file_serve',
        'ppxai.server.routes.files',
        'ppxai.server.routes.preview',
        'ppxai.server.routes.providers',
        'ppxai.server.routes.schema',
        'ppxai.server.routes.sessions',
        'ppxai.server.routes.state',
        'ppxai.server.routes.static',
        'ppxai.server.routes.terminal',
        'ppxai.server.routes.usage',
        'ppxai.server.session_manager',
        'ppxai.common.preview',
        'ppxai.common.atomic_file',  # v1.18.0 Phase 5g
        'ppxai.common.docx_to_pdf',  # v1.18.0 Phase 5g
        'ppxai.common.format',        # v1.18.0 Phase 4
        'ppxai.common.autosave_guard',  # v1.18.0 Phase 5f
        # Engine modules added in v1.17.4
        'ppxai.version',
        'ppxai.engine.app_state',
        'ppxai.engine.completion',
        'ppxai.engine.session_store',
        'ppxai.engine.file_preprocessing',
        'ppxai.engine.image_validation',
        'ppxai.engine.model_deprecations',
        'ppxai.engine.model_profiles',
        'ppxai.engine.bootstrap_ops',
        'ppxai.engine.checkpoint_ops',
        'ppxai.engine.consent_ops',
        # Command system. CRITICAL: list every module in
        # _BUILTIN_COMMAND_MODULES (ppxai/commands/factory.py:26).
        # The factory's `_ensure_loaded` uses `importlib.import_module(string)`
        # which PyInstaller can't see at static-analysis time. Without
        # explicit hidden imports, the frozen binary's CommandFactory
        # registry is empty and every `POST /command/<name>` returns
        # "Unknown command" (the bug surfaced post-v1.18.0 release).
        'ppxai.commands',
        'ppxai.commands.factory',
        'ppxai.commands.handler',
        'ppxai.commands.context',
        'ppxai.commands.protocol',
        'ppxai.commands.results',
        'ppxai.commands.session',
        'ppxai.commands.provider',
        'ppxai.commands.system',
        'ppxai.commands.coding',
        'ppxai.commands.utility',
        'ppxai.commands.agent',
        'ppxai.commands.tools',
        'ppxai.commands.display',
        'ppxai.commands.attach',
        'ppxai.commands.doctor',
        # Tool modules (v1.17.4 — data file tools)
        'ppxai.engine.tools.builtin',
        'ppxai.engine.tools.builtin.pdf_tools',
        'ppxai.engine.tools.builtin.excel_tools',
        'ppxai.engine.tools.builtin.pptx_tools',
        'ppxai.engine.tools.builtin.docx_tools',
        'ppxai.engine.tools.builtin.csv_tools',
        # [data] extras — optional but bundle when available
        'pypdf',
        # v1.18.1: pypdfium2 replaces pdf2image+poppler. Pure-wheel,
        # bundles a self-contained PDFium binary, so PyInstaller
        # output works without a system poppler install.
        'pypdfium2',
        'openpyxl',
        'pptx',
        # Timezone support
        'tzdata',
        'zoneinfo',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['rthooks/rthook_sigint.py'],
    excludes=[
        # Exclude development/testing packages
        'pytest',
        'pytest_asyncio',
        'ruff',
        # Exclude tkinter (not needed for server)
        'tkinter',
        '_tkinter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ppxai-server',
    debug=False,
    bootloader_ignore_signals=True,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/ppxai.ico',
)
