"""Write ppxai/_build_info.py from the current git state.

Called by release tooling (or by the dev) just before PyInstaller runs.
The generated module exposes `BUILD_COMMIT` and `BUILD_MTIME`, which
`ppxai/version.py::_build_info()` reads in preference to its runtime
probes (`git rev-parse`, source-mtime scan).

PyInstaller bundles `_build_info.py` into the binary because
`ppxai.version` is a hiddenimport in every spec file and the build_info
module sits next to it in the same package. The bundled binary then
reports the real commit hash and build time — not "n/a, n/a" — even
after the source tree is gone.

The file is gitignored. Generate it before each PyInstaller invocation;
delete it after if you want clean dev runs to fall through to runtime
probes (the runtime path correctly identifies dev edits).
"""
from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent

    # Short commit hash. Falls back to "unknown" if not a git checkout.
    try:
        commit = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        ).stdout.strip()
    except (FileNotFoundError, subprocess.SubprocessError, OSError):
        commit = ""
    if not commit:
        commit = "unknown"

    mtime = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    out = repo_root / "ppxai" / "_build_info.py"
    out.write_text(
        f'"""Generated by scripts/write_build_info.py — DO NOT EDIT.\n'
        f'\n'
        f'PyInstaller bundles this file into the binary so the runtime\n'
        f'banner can show the real build commit + time even when git\n'
        f'and the source tree are gone.\n'
        f'"""\n'
        f'\n'
        f'BUILD_COMMIT = {commit!r}\n'
        f'BUILD_MTIME = {mtime!r}\n',
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(repo_root)} commit={commit} mtime={mtime}")


if __name__ == "__main__":
    main()
