---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ppxai.namespace" . }}
  labels:
    {{- include "ppxai.labels" . | nindent 4 }}
    {{- with .Values.namespaceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
