{{- if not .Values.registry.external }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: {{ include "ppxai.namespace" . }}
  labels:
    {{- include "ppxai.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: {{ include "ppxai.namespace" . }}
  labels:
    {{- include "ppxai.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  selector:
    app: registry
  ports:
    - port: {{ .Values.registry.port | default 5000 }}
      targetPort: 5000
  type: ClusterIP
{{- end }}
