---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ppxai.fullname" . }}-registry
  namespace: {{ include "ppxai.namespace" . }}
  labels:
    {{- include "ppxai.labels" . | nindent 4 }}
    app.kubernetes.io/component: session-manager
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.registryStorageClass | default .Values.storageClass.workspaceName }}
  resources:
    requests:
      storage: {{ .Values.storage.registrySize }}
